name: box_it_up
version: 0.1.0
author: Vostrikov Vitaliy <rasart.pro@gmail.com>
homepage: http://rasarts.github.io/BoxItUp/
description: displaying images, html content and multi-media
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
